### ISSUE TITLE
Come up with a visual theme concept

### ISSUE THREAD

**Issue by SaltedHQ** [SleddGang/ContentMod#12]
**Due:** 01/18/2020

Backgrounds, enemies, items, what is the overall color scheme, shape, and vibe that we wants these things to take?

**Comment by alecrm** [comment]
From @SaltedHQ:

"Nothing physical to share but a couple thoughts and ideas for the visual theme, will be a little hard to come up with something until we have a little more of a plan"

Bumping deadline out two weeks

**Comment by SaltedBiscuit** [comment]
Color scheme done, sketches to come when i have time.
Overall color palette is black (or a dark, color-tinted gray) with neon blue or neon pink/magenta glowing highlights. Lots of tendrils, eyeballs, orbs. A theme straight out of a lovecraftian nightmare.
