### ISSUE TITLE
Update Github Repo to Void

### ISSUE THREAD

**Issue by alecrm** [SleddGang/ContentMod#21]
**Due Date:** 01/18/2021

- We want to update the SleddGang/ContentMod repo to be SleddGang/Void

- We also want to update the actual code repo to be named Void

**Comment by benjazzy** [comment]
Steps to update your local repository name:

- Open Visual Studio and select Team Explorer on the right.
- Select Settings under Project.
- Select Repository Settings.
- Under Remotes select Edit and change Fetch to https://github.com/SleddGang/Void.git and make sure Push matches fetch is checked.
- Click Save and close Visual Studio.
- Open Documents\My Games\Terraria\ModLoader\Mod Sources and rename ContentMod to Void.
- Open up Visual Studio and open up the solution in the updated mod folder.
